/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.pkg2;

import javax.swing.*;     // Para la interfaz (JFrame, JPanel, etc.)
import java.awt.*;       // Para el dibujo (Graphics, Color, Font)
import java.io.*;        // Por si usas archivos


public class VentanaPrincipal extends javax.swing.JFrame {

    // ESTOS SON TUS ATRIBUTOS (El motor y el lienzo)
    private  GestorImpresion gestor = new GestorImpresion();
    private JPanel lienzoArbol;

    public VentanaPrincipal() {
        initComponents(); // ESTO NO LO BORRES, es de NetBeans
        
        // PEGA ESTO AQUÍ: Conecta el código con tu cuadro gris (jScrollPane1)
        configurarLienzoArbol(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JToggleButton();
        btnImprimir = new javax.swing.JToggleButton();
        btnCargar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        chkPrio = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        txtDoc = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Nombre del Documento:");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        btnEnviar.setText("Enviar Documento");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnviar, java.awt.BorderLayout.PAGE_END);

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(btnImprimir, java.awt.BorderLayout.LINE_END);

        btnCargar.setText("Cargar CSV");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCargar, java.awt.BorderLayout.LINE_START);

        jLabel2.setText("Nombre Usuario:");
        jPanel1.add(jLabel2, java.awt.BorderLayout.CENTER);

        jLabel3.setText("Tamaño(pag):");
        jPanel1.add(jLabel3, java.awt.BorderLayout.CENTER);
        jPanel1.add(jLabel4, java.awt.BorderLayout.CENTER);
        jPanel1.add(txtSize, java.awt.BorderLayout.CENTER);

        chkPrio.setText("¿Es prioritario?");
        jPanel1.add(chkPrio, java.awt.BorderLayout.CENTER);

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane2.setViewportView(txtArea);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);
        jPanel1.add(txtDoc, java.awt.BorderLayout.CENTER);
        jPanel1.add(txtUser, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        try {
        // Sacamos los datos de la interfaz
        String nombreDoc = txtDoc.getText();
        String nombreUser = txtUser.getText();
        int tamaño = Integer.parseInt(txtSize.getText());
        boolean esPrioritario = chkPrio.isSelected();

        // Validamos que no estén vacíos
        if (!nombreDoc.isEmpty() && !nombreUser.isEmpty()) {
            
            // AQUÍ SE USA EL GESTOR:
            gestor.agregarDocumento(nombreDoc, nombreUser, esPrioritario, tamaño);
            
            // Refrescamos la pantalla (esto también usa el gestor internamente)
            actualizarVista();
            
            // Limpiamos los campos
            txtDoc.setText("");
            txtUser.setText("");
            txtSize.setText("");
            chkPrio.setSelected(false);
            
        } else {
            JOptionPane.showMessageDialog(this, "Por favor llena todos los campos.");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El tamaño debe ser un número válido.");
    }

    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
  Documento doc = gestor.imprimirSiguiente();
    if (doc != null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Imprimiendo: " + doc.getNombre());
        actualizarVista();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "No hay documentos en cola.");
    }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed

    JFileChooser chooser = new JFileChooser();
    if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
        File archivo = chooser.getSelectedFile(); // <--- USA java.io.File
        
        try (BufferedReader br = new BufferedReader(new FileReader(archivo))) { // <--- USA java.io.FileReader
            String linea;
            while ((linea = br.readLine()) != null) {
                // Supongamos que el CSV es: Nombre,Prioridad
                String[] partes = linea.split(",");
                if (partes.length >= 2) {
                    gestor.registrarUsuario(partes[0].trim(), partes[1].trim());
                }
            }
            JOptionPane.showMessageDialog(this, "Usuarios cargados desde el archivo.");
            actualizarVista();
        } catch (IOException e) { // <--- USA java.io.IOException
            JOptionPane.showMessageDialog(this, "Error al leer: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnCargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JToggleButton btnEnviar;
    private javax.swing.JToggleButton btnImprimir;
    private javax.swing.JCheckBox chkPrio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtDoc;
    private javax.swing.JTextField txtSize;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
// --- MOTOR DE INTERFAZ (PEGA TODO ESTO JUNTO) ---

    private void configurarLienzoArbol() {
        lienzoArbol = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                dibujarArbolGrafico(g);
            }
        };
        
        lienzoArbol.setBackground(new Color(43, 45, 49)); // Color oscuro
        lienzoArbol.setPreferredSize(new Dimension(2000, 1000));
        
        // Conecta el lienzo con el cuadro gris de tu diseño
        jScrollPane1.setViewportView(lienzoArbol);
    }

    public void actualizarVista() {
        if (gestor == null || gestor.getCola() == null) return;

        // 1. Actualizar el JTextArea (Lista de texto)
        StringBuilder sb = new StringBuilder("--- COLA DE IMPRESIÓN ---\n");
        Documento[] docs = gestor.getCola().getArreglo();
        int tam = gestor.getCola().getTamaño();

        for (int i = 0; i < tam; i++) {
            if (docs[i] != null) {
                sb.append(i + 1).append(". ").append(docs[i].getNombre())
                  .append(" [Prioridad: ").append(docs[i].getEtiquetaTiempo()).append("]\n");
            }
        }
        txtArea.setText(sb.toString());

        // 2. Forzar el redibujo del árbol
        if (lienzoArbol != null) {
            lienzoArbol.revalidate();
            lienzoArbol.repaint();
        }
    }

    private void dibujarArbolGrafico(Graphics g) {
        if (gestor == null || gestor.getCola().getTamaño() == 0) return;
        
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        
        // Calculamos el centro dinámico según el tamaño actual del panel
        int xRaiz = lienzoArbol.getWidth() / 2;
        pintarNodo(g2, 0, xRaiz, 50, xRaiz / 2);
    }

    private void pintarNodo(Graphics2D g, int i, int x, int y, int esp) {
        if (i >= gestor.getCola().getTamaño()) return;

        int radio = 20;
        
        // Dibujar líneas a los hijos primero (para que queden detrás de los círculos)
        g.setColor(Color.WHITE);
        if (2 * i + 1 < gestor.getCola().getTamaño()) {
            g.drawLine(x, y, x - esp, y + 60);
            pintarNodo(g, 2 * i + 1, x - esp, y + 60, esp / 2);
        }
        if (2 * i + 2 < gestor.getCola().getTamaño()) {
            g.drawLine(x, y, x + esp, y + 60);
            pintarNodo(g, 2 * i + 2, x + esp, y + 60, esp / 2);
        }

        // Dibujar el círculo (Nodo)
        g.setColor(new Color(114, 137, 218)); // Color azulado
        g.fillOval(x - radio, y - radio, radio * 2, radio * 2);
        g.setColor(Color.WHITE);
        g.drawOval(x - radio, y - radio, radio * 2, radio * 2);

        // Dibujar el número de prioridad
        String valor = String.valueOf(gestor.getCola().getArreglo()[i].getEtiquetaTiempo());
        FontMetrics fm = g.getFontMetrics();
        int textoX = x - (fm.stringWidth(valor) / 2);
        int textoY = y + (fm.getAscent() / 2) - 2;
        g.drawString(valor, textoX, textoY);
    }
}
